# Metrics selection

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn.metrics as metrics

In [2]:
train = pd.read_csv("../data/trainp.csv")
dev = pd.read_csv("../data/devp.csv")
test= pd.read_csv("../data/testp.csv")

In [6]:
test

,id,monthly_oilprice_avg,BEVERAGES,POULTRY,GROCERY.I,CLEANING,store_typeA,store_typeD,city_Guayaquil,total_city_sales.x,sales_perc.x,cluster8,top5_item,class1040,class1072,year2017,month8,item_per,store_per,total_unit_sales
0,8,0.833328,0,0,1,0,0,1,0,0.800121,0.507967,0,0,0,0,0,0,0.001346,0.022585,4.043051
1,21,0.221588,0,0,1,0,0,1,0,0.866210,0.490651,0,0,0,0,0,0,0.001346,0.022585,3.784190
2,22,0.265722,0,0,1,0,0,1,0,0.779034,0.478646,0,0,0,0,0,0,0.001346,0.022585,4.262680
3,31,0.158958,0,0,1,0,0,1,0,0.858906,0.486089,0,0,0,0,0,0,0.001346,0.022585,3.806662
4,44,0.283902,0,0,1,0,0,1,0,0.958049,0.470372,0,0,0,0,0,0,0.001346,0.022585,5.659482
5,59,0.920859,0,0,1,0,0,0,0,0.754731,0.495428,0,0,0,0,0,0,0.001346,0.020851,3.850148
6,65,0.942353,0,0,1,0,0,0,0,0.855275,0.506752,0,0,0,0,0,0,0.001346,0.020851,4.828314
7,66,0.989791,0,0,1,0,0,0,0,0.843750,0.502152,0,0,0,0,0,0,0.001346,0.020851,4.584967
8,67,0.960864,0,0,1,0,0,0,0,0.858392,0.484502,0,0,0,0,0,0,0.001346,0.020851,4.204693
9,72,0.379902,0,0,1,0,0,0,0,1.000000,0.469316,0,0,0,0,0,0,0.001346,0.020851,5.793014
10,75,0.229517,0,0,1,0,0,0,0,0.907323,0.496496,0,0,0,0,0,0,0.001346,0.020851,4.110874
11,79,0.269875,0,0,1,0,0,0,0,0.871057,0.470743,0,0,0,0,0,0,0.001346,0.020851,4.143135
12,94,0.255112,0,0,1,0,0,0,0,0.801854,0.483059,0,0,0,0,0,0,0.001346,0.020851,3.970292
13,115,0.924342,0,0,1,0,0,0,0,0.059553,0.032992,0,0,0,0,0,0,0.001346,0.022453,5.164786
14,127,0.229517,0,0,1,0,0,0,0,0.053000,0.030298,0,0,0,0,0,0,0.001346,0.022453,5.129899
15,130,0.386841,0,0,1,0,0,0,0,0.052746,0.030353,0,0,0,0,0,0,0.001346,0.022453,5.236442
16,150,0.303548,0,0,1,0,0,0,0,0.046482,0.031430,0,0,0,0,1,0,0.001346,0.022453,5.680173
17,160,0.975058,0,0,1,0,0,0,0,0.040004,0.028789,0,0,0,0,0,0,0.001346,0.021092,4.584967
18,165,0.882655,0,0,1,0,0,0,0,0.046740,0.026168,0,0,0,0,0,0,0.001346,0.021092,5.641907
19,169,0.942353,0,0,1,0,0,0,0,0.044127,0.027558,0,0,0,0,0,0,0.001346,0.021092,5.214936
20,179,0.229517,0,0,1,0,0,0,0,0.048203,0.027681,0,0,0,0,0,0,0.001346,0.021092,4.510860
21,191,0.136817,0,0,1,0,0,0,0,0.046984,0.024945,0,0,0,0,0,0,0.001346,0.021092,4.653960
22,193,0.241762,0,0,1,0,0,0,0,0.035147,0.024097,0,0,0,0,0,0,0.001346,0.021092,4.779123
23,217,0.843205,0,0,1,0,0,0,0,0.044430,0.026957,0,0,0,0,0,0,0.001346,0.020975,4.219508
24,236,0.198775,0,0,1,0,0,0,0,0.049206,0.026672,0,0,0,0,0,0,0.001346,0.020975,4.465908
25,246,0.187915,0,0,1,0,0,0,0,0.037009,0.023538,0,0,0,0,0,0,0.001346,0.020975,4.174387
26,250,0.201154,0,0,1,0,0,0,0,0.039857,0.023950,0,0,0,0,0,0,0.001346,0.020975,4.262680
27,279,0.379902,0,0,1,0,0,0,0,0.025966,0.013336,0,0,0,0,0,0,0.001346,0.020886,5.700444
28,282,0.229517,0,0,1,0,0,0,0,0.021197,0.012943,0,0,0,0,0,0,0.001346,0.020886,4.276666
29,293,0.000000,0,0,1,0,0,0,0,0.018468,0.012703,0,0,0,0,0,0,0.001346,0.020886,4.736198
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173743,1974956,0.265722,0,0,0,1,0,1,0,0.014029,0.010136,0,0,0,0,0,0,0.001270,0.016519,4.158883
173744,1974958,0.316458,0,0,0,1,0,1,0,0.014049,0.009461,0,0,0,0,0,0,0.001270,0.016519,4.290459
173745,1974968,0.000000,0,0,0,1,0,1,0,0.014257,0.010154,0,0,0,0,0,0,0.001270,0.016519,4.330733
173746,1974973,0.187915,0,0,0,1,0,1,0,0.035214,0.022470,0,0,0,0,0,0,0.001270,0.016519,5.181784
173747,1974979,0.249245,0,0,0,1,0,1,0,0.020913,0.013011,0,0,0,0,1,0,0.001270,0.016519,4.644391
173748,1974985,0.809162,0,0,0,1,0,0,0,0.015945,0.012628,0,0,0,0,0,0,0.001270,0.020166,4.836282
173749,1974990,0.996286,0,0,0,1,0,0,0,0.017254,0.012763,0,0,0,0,0,0,0.001270,0.020166,4.394449
173750,1975003,0.596284,0,0,0,1,0,0,0,0.021732,0.013017,0,0,0,0,0,0,0.001270,0.020166,4.663439
173751,1975007,0.229517,0,0,0,1,0,0,0,0.020313,0.012461,0,0,0,0,0,0,0.001270,0.020166,4.744932
173752,1975009,0.379569,0,0,0,1,0,0,0,0.022906,0.013075,0,0,0,0,0,0,0.001270,0.020166,4.744932
173753,1975011,0.269875,0,0,0,1,0,0,0,0.021875,0.013147,0,0,0,0,0,0,0.001270,0.020166,4.605170
173754,1975018,0.000000,0,0,0,1,0,0,0,0.017615,0.012186,0,0,0,0,0,0,0.001270,0.020166,4.718499
173755,1975021,0.214943,0,0,0,1,0,0,0,0.022672,0.013976,0,0,0,0,0,0,0.001270,0.020166,4.795791
173756,1975036,0.232315,0,0,0,1,0,0,0,0.008630,0.013610,0,0,0,0,1,1,0.001270,0.020166,4.094345
173757,1975053,0.824775,0,0,0,1,0,1,0,0.904300,0.503664,0,0,0,0,0,0,0.001270,0.023246,5.455321
173758,1975055,0.596284,0,0,0,1,0,1,0,0.915668,0.492773,0,0,0,0,0,0,0.001270,0.023246,5.693732
173759,1975062,0.386841,0,0,0,1,0,1,0,0.876196,0.482579,0,0,0,0,0,0,0.001270,0.023246,5.375278
173760,1975063,0.269875,0,0,0,1,0,1,0,0.871057,0.470743,0,0,0,0,0,0,0.001270,0.023246,5.293305
173761,1975066,0.208534,0,0,0,1,0,1,0,0.885446,0.471846,0,0,0,0,0,0,0.001270,0.023246,5.673323
173762,1975081,0.290899,0,0,0,1,0,1,0,0.858397,0.487247,0,0,0,0,1,0,0.001270,0.023246,5.973810
173763,1975096,0.833328,0,0,0,1,0,1,0,0.800121,0.507967,1,0,0,0,0,0,0.001270,0.022727,6.228511
173764,1975106,0.709169,0,0,0,1,0,1,0,0.902293,0.495543,1,0,0,0,0,0,0.001270,0.022727,6.423247
173765,1975120,0.090041,0,0,0,1,0,1,0,0.927394,0.459680,1,0,0,0,0,0,0.001270,0.022727,7.032624
173766,1975132,0.283902,0,0,0,1,0,1,0,0.958049,0.470372,1,0,0,0,0,0,0.001270,0.022727,6.703188
173767,1975154,0.989791,0,0,0,1,0,1,0,0.843750,0.502152,1,0,0,0,0,0,0.001270,0.023362,6.682109
173768,1975158,0.709169,0,0,0,1,0,1,0,0.902293,0.495543,1,0,0,0,0,0,0.001270,0.023362,6.951772
173769,1975176,0.136817,0,0,0,1,0,1,0,0.988490,0.499353,1,0,0,0,0,0,0.001270,0.023362,6.190315
173770,1975182,0.255112,0,0,0,1,0,1,0,0.801854,0.483059,1,0,0,0,0,0,0.001270,0.023362,6.021023
173771,1975201,0.882655,0,0,0,1,0,0,0,0.911430,0.485479,0,0,0,0,0,0,0.001270,0.022969,5.529429
173772,1975215,0.379569,0,0,0,1,0,0,0,0.954358,0.492046,0,0,0,0,0,0,0.001270,0.022969,6.001415

In [25]:
varsel = pd.read_csv("../data/varsel.csv")

In [26]:
varsel.head()

,Unnamed: 0,Variable,Lasso,Ridge,RandomForest,GradientBoost,Linear Regression,Ada Boost,dtree,Sum
0,0,monthly_oilprice_avg,0,0,1,0,0,0,1,2
1,1,total_month_holidays,0,0,0,0,0,0,0,0
2,2,perishable,0,0,0,1,0,0,0,1
3,3,BREAD.BAKERY,0,0,0,0,0,0,0,0
4,4,BEVERAGES,0,0,1,1,0,1,1,4

In [27]:
v2 = varsel.loc[varsel['Sum']>=2]['Variable'].tolist()
v3 = varsel.loc[varsel['Sum']>=3]['Variable'].tolist()
v4 = varsel.loc[varsel['Sum']>=4]['Variable'].tolist()

In [6]:
v4

['BEVERAGES',
 'CLEANING',
 'store_typeA',
 'total_city_sales.x',
 'sales_perc.x',
 'cluster8',
 'top5_item',
 'class1040',
 'class1072',
 'item_per',
 'store_per']

## Linear Regression

In [28]:
train.head()

,id,monthly_oilprice_avg,BEVERAGES,POULTRY,GROCERY.I,CLEANING,store_typeA,store_typeD,city_Guayaquil,total_city_sales.x,sales_perc.x,cluster8,top5_item,class1040,class1072,year2017,month8,item_per,store_per,total_unit_sales
0,1474241,0.201154,0,0,0,0,0,0,0,0.083314,0.048508,0,0,0,0,0,0,0.001325,0.023096,3.688879
1,973784,0.229517,0,0,1,0,0,0,0,0.021197,0.012943,0,0,0,0,0,0,0.001186,0.020886,3.891820
2,1458848,0.269875,0,0,0,0,0,0,1,0.228751,0.124626,0,0,0,0,0,0,0.001323,0.022468,3.258097
3,185972,0.942353,0,0,0,1,0,1,0,0.028841,0.018528,0,0,0,0,0,0,0.001161,0.022039,5.023881
4,483059,0.229517,0,0,0,0,0,0,0,0.021197,0.012943,0,0,0,0,0,0,0.000969,0.020886,4.852030

In [29]:
X2= train.loc[:, v2]
X3= train.loc[:, v3]
X4= train.loc[:, v4]
y = train.loc[:,'total_unit_sales']

In [30]:
Xdev2= dev.loc[:, v2]
Xdev3= dev.loc[:, v3]
Xdev4= dev.loc[:, v4]
ydev = dev.loc[:,'total_unit_sales']

In [31]:
from sklearn.linear_model import LinearRegression
lrmod2 = LinearRegression().fit(X2,y)

In [32]:
y_hat2 = lrmod2.predict(X2)
ydev_hat2 = lrmod2.predict(Xdev2)

In [33]:
print('MSE= %f' % metrics.mean_squared_error(y,y_hat2))#, squared=False)) <--- version 0.22 +
print('RMSE= %f' % np.sqrt(metrics.mean_squared_error(y,y_hat2)))
print('MAE= %f' % metrics.mean_absolute_error(y,y_hat2))
print('MSLE= %f' % metrics.mean_squared_log_error(y,y_hat2))
print('R2= %f' % metrics.r2_score(y,y_hat2))

MSE= 0.908753
RMSE= 0.953285
MAE= 0.755750
MSLE= 0.030693
R2= 0.127223

In [35]:
MSE1A = metrics.mean_squared_error(y,y_hat2)
RMSE1A = np.sqrt(metrics.mean_squared_error(y,y_hat2))
MAE1A = metrics.mean_absolute_error(y,y_hat2)
MSLE1A = metrics.mean_squared_log_error(y,y_hat2)
R21A = metrics.r2_score(y,y_hat2)

In [37]:
print('MSE= %f' % metrics.mean_squared_error(ydev,ydev_hat2))#, squared=False)) <--- version 0.22 +
print('RMSE= %f' % np.sqrt(metrics.mean_squared_error(ydev,ydev_hat2)))
print('MAE= %f' % metrics.mean_absolute_error(ydev,ydev_hat2))
print('MSLE= %f' % metrics.mean_squared_log_error(ydev,ydev_hat2))
print('R2= %f' % metrics.r2_score(ydev,ydev_hat2))

MSE= 0.911509
RMSE= 0.954730
MAE= 0.756612
MSLE= 0.030846
R2= 0.127054

In [38]:
MSE1B = metrics.mean_squared_error(ydev,ydev_hat2)
RMSE1B = np.sqrt(metrics.mean_squared_error(ydev,ydev_hat2))
MAE1B = metrics.mean_absolute_error(ydev,ydev_hat2)
MSLE1B = metrics.mean_squared_log_error(ydev,ydev_hat2)
R21B = metrics.r2_score(ydev,ydev_hat2)

In [14]:
lrmod3 = LinearRegression().fit(X3,y)
lrmod3.score(X3,y)

0.11572353389710811

In [15]:
y_hat3 = lrmod3.predict(X3)

In [16]:
print('MSE= %f' % metrics.mean_squared_error(y,y_hat3))#, squared=False)) <--- version 0.22 +
print('RMSE= %f' % np.sqrt(metrics.mean_squared_error(y,y_hat3)))
print('MAE= %f' % metrics.mean_absolute_error(y,y_hat3))
print('MSLE= %f' % metrics.mean_squared_log_error(y,y_hat3))
print('R2= %f' % metrics.r2_score(y,y_hat3))

MSE= 0.920726
RMSE= 0.959545
MAE= 0.761314
MSLE= 0.031075
R2= 0.115724

In [17]:
lrmod4 = LinearRegression().fit(X4,y)
lrmod4.score(X4,y)

0.10736331074452654

In [18]:
y_hat4 = lrmod4.predict(X4)

In [19]:
print('MSE= %f' % metrics.mean_squared_error(y,y_hat4))#, squared=False)) <--- version 0.22 +
print('RMSE= %f' % np.sqrt(metrics.mean_squared_error(y,y_hat4)))
print('MAE= %f' % metrics.mean_absolute_error(y,y_hat4))
print('MSLE= %f' % metrics.mean_squared_log_error(y,y_hat4))
print('R2= %f' % metrics.r2_score(y,y_hat4))

MSE= 0.929431
RMSE= 0.964070
MAE= 0.764505
MSLE= 0.031409
R2= 0.107363

###  Random Forest

In [39]:
from sklearn.ensemble import RandomForestRegressor
rfmod2 = RandomForestRegressor().fit(X2, y)
#rfmod.feature_importances_

C:\Users\Guy\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [40]:
y_hat2 = rfmod2.predict(X2)

In [41]:
print('MSE= %f' % metrics.mean_squared_error(y,y_hat2))#, squared=False)) <--- version 0.22 +
print('RMSE= %f' % np.sqrt(metrics.mean_squared_error(y,y_hat2)))
print('MAE= %f' % metrics.mean_absolute_error(y,y_hat2))
print('MSLE= %f' % metrics.mean_squared_log_error(y,y_hat2))
print('R2= %f' % metrics.r2_score(y,y_hat2))

MSE= 0.139675
RMSE= 0.373732
MAE= 0.227872
MSLE= 0.004868
R2= 0.865854

In [42]:
MSE2A = metrics.mean_squared_error(y,y_hat2)
RMSE2A = np.sqrt(metrics.mean_squared_error(y,y_hat2))
MAE2A = metrics.mean_absolute_error(y,y_hat2)
MSLE2A = metrics.mean_squared_log_error(y,y_hat2)
R22A = metrics.r2_score(y,y_hat2)

In [43]:
ydev_hat2 = rfmod2.predict(Xdev2)

In [44]:
print('MSE= %f' % metrics.mean_squared_error(ydev,ydev_hat2))#, squared=False)) <--- version 0.22 +
print('RMSE= %f' % np.sqrt(metrics.mean_squared_error(ydev,ydev_hat2)))
print('MAE= %f' % metrics.mean_absolute_error(ydev,ydev_hat2))
print('MSLE= %f' % metrics.mean_squared_log_error(ydev,ydev_hat2))
print('R2= %f' % metrics.r2_score(ydev,ydev_hat2))

MSE= 0.425077
RMSE= 0.651980
MAE= 0.446759
MSLE= 0.014937
R2= 0.592907

In [45]:
MSE2B = metrics.mean_squared_error(ydev,ydev_hat2)
RMSE2B = np.sqrt(metrics.mean_squared_error(ydev,ydev_hat2))
MAE2B = metrics.mean_absolute_error(ydev,ydev_hat2)
MSLE2B = metrics.mean_squared_log_error(ydev,ydev_hat2)
R22B = metrics.r2_score(ydev,ydev_hat2)

In [23]:
from sklearn.ensemble import RandomForestRegressor
rfmod3 = RandomForestRegressor().fit(X3, y)

C:\Users\Guy\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [24]:
y_hat3 = rfmod3.predict(X3)

In [25]:
print('MSE= %f' % metrics.mean_squared_error(y,y_hat3))#, squared=False)) <--- version 0.33 +
print('RMSE= %f' % np.sqrt(metrics.mean_squared_error(y,y_hat3)))
print('MAE= %f' % metrics.mean_absolute_error(y,y_hat3))
print('MSLE= %f' % metrics.mean_squared_log_error(y,y_hat3))
print('RMSLE= %f' % np.sqrt(metrics.mean_squared_log_error(y,y_hat3)))
print('R2= %f' % metrics.r2_score(y,y_hat3))

MSE= 0.196438
RMSE= 0.443214
MAE= 0.282383
MSLE= 0.006768
RMSLE= 0.082270
R2= 0.811338

In [48]:
ydev_hat3 = rfmod3.predict(Xdev3)

In [49]:
print('MSE= %f' % metrics.mean_squared_error(ydev,ydev_hat3))#, squared=False)) <--- version 0.33 +
print('RMSE= %f' % np.sqrt(metrics.mean_squared_error(ydev,ydev_hat3)))
print('MAE= %f' % metrics.mean_absolute_error(ydev,ydev_hat3))
print('MSLE= %f' % metrics.mean_squared_log_error(ydev,ydev_hat3))
print('RMSLE= %f' % np.sqrt(metrics.mean_squared_log_error(ydev,ydev_hat3)))
print('R2= %f' % metrics.r2_score(ydev,ydev_hat3))

MSE= 0.557160
RMSE= 0.746431
MAE= 0.526641
MSLE= 0.019236
RMSLE= 0.138694
R2= 0.466412

In [29]:
from sklearn.ensemble import RandomForestRegressor
rfmod4 = RandomForestRegressor().fit(X4, y)

C:\Users\Guy\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [27]:
y_hat4 = rfmod4.predict(X4)

In [28]:
print('MSE= %f' % metrics.mean_squared_error(y,y_hat4))#, squared=False)) <--- version 0.44 +
print('RMSE= %f' % np.sqrt(metrics.mean_squared_error(y,y_hat4)))
print('MAE= %f' % metrics.mean_absolute_error(y,y_hat4))
print('MSLE= %f' % metrics.mean_squared_log_error(y,y_hat4))
print('RMSLE= %f' % np.sqrt(metrics.mean_squared_log_error(y,y_hat4)))
print('R2= %f' % metrics.r2_score(y,y_hat4))

MSE= 0.196484
RMSE= 0.443265
MAE= 0.282336
MSLE= 0.006767
RMSLE= 0.082261
R2= 0.811294

 after i saw that threshold= 2 gives us the best scores by training 2 models i decided to continue with this

### XGboost

In [46]:
from xgboost.sklearn import XGBRegressor

In [47]:
params = {'objective':'reg:linear', 'max_depth':6, 'learning_rate':1,
         'n_estimators':5}

In [48]:
xgb = XGBRegressor(**params).fit(X2,y)

[23:59:42] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.1.0/src/objective/regression_obj.cu:168: reg:linear is now deprecated in favor of reg:squarederror.
[00:00:00] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.1.0/src/objective/regression_obj.cu:168: reg:linear is now deprecated in favor of reg:squarederror.

In [49]:
y_hat2= xgb.predict(X2)

In [50]:
print('MSE= %f' % metrics.mean_squared_error(y,y_hat2))#, squared=False)) <--- version 0.44 +
print('RMSE= %f' % np.sqrt(metrics.mean_squared_error(y,y_hat2)))
print('MAE= %f' % metrics.mean_absolute_error(y,y_hat2))
print('MSLE= %f' % metrics.mean_squared_log_error(y,y_hat2))
print('R2= %f' % metrics.r2_score(y,y_hat2))

MSE= 0.737664
RMSE= 0.858874
MAE= 0.672583
MSLE= 0.025105
R2= 0.291539

In [51]:
MSE3A = metrics.mean_squared_error(y,y_hat2)
RMSE3A = np.sqrt(metrics.mean_squared_error(y,y_hat2))
MAE3A = metrics.mean_absolute_error(y,y_hat2)
MSLE3A = metrics.mean_squared_log_error(y,y_hat2)
R23A = metrics.r2_score(y,y_hat2)

In [52]:
ydev_hat2= xgb.predict(Xdev2)

In [53]:
print('MSE= %f' % metrics.mean_squared_error(ydev,ydev_hat2))#, squared=False)) <--- version 0.44 +
print('RMSE= %f' % np.sqrt(metrics.mean_squared_error(ydev,ydev_hat2)))
print('MAE= %f' % metrics.mean_absolute_error(ydev,ydev_hat2))
print('MSLE= %f' % metrics.mean_squared_log_error(ydev,ydev_hat2))
print('RMSLE= %f' % np.sqrt(metrics.mean_squared_log_error(ydev,ydev_hat2)))
print('R2= %f' % metrics.r2_score(ydev,ydev_hat2))

MSE= 0.742225
RMSE= 0.861525
MAE= 0.674458
MSLE= 0.025319
RMSLE= 0.159120
R2= 0.289177

In [54]:
MSE3B = metrics.mean_squared_error(ydev,ydev_hat2)
RMSE3B = np.sqrt(metrics.mean_squared_error(ydev,ydev_hat2))
MAE3B = metrics.mean_absolute_error(ydev,ydev_hat2)
MSLE3B = metrics.mean_squared_log_error(ydev,ydev_hat2)
R23B = metrics.r2_score(ydev,ydev_hat2)

# Ada Boost

In [55]:
from sklearn.ensemble import AdaBoostRegressor
ABRmod2 = AdaBoostRegressor(random_state=1).fit(X2,y)

In [56]:
y_hat2 = ABRmod2.predict(X2)

In [57]:
print('MSE= %f' % metrics.mean_squared_error(y,y_hat2))#, squared=False)) <--- version 0.44 +
print('RMSE= %f' % np.sqrt(metrics.mean_squared_error(y,y_hat2)))
print('MAE= %f' % metrics.mean_absolute_error(y,y_hat2))
print('MSLE= %f' % metrics.mean_squared_log_error(y,y_hat2))
print('R2= %f' % metrics.r2_score(y,y_hat2))

MSE= 0.937782
RMSE= 0.968391
MAE= 0.768766
MSLE= 0.031287
R2= 0.099343

In [58]:
MSE4A = metrics.mean_squared_error(y,y_hat2)
RMSE4A = np.sqrt(metrics.mean_squared_error(y,y_hat2))
MAE4A = metrics.mean_absolute_error(y,y_hat2)
MSLE4A = metrics.mean_squared_log_error(y,y_hat2)
R24A = metrics.r2_score(y,y_hat2)

In [59]:
ydev_hat2 = ABRmod2.predict(Xdev2)

In [60]:
print('MSE= %f' % metrics.mean_squared_error(ydev,ydev_hat2))#, squared=False)) <--- version 0.44 +
print('RMSE= %f' % np.sqrt(metrics.mean_squared_error(ydev,ydev_hat2)))
print('MAE= %f' % metrics.mean_absolute_error(ydev,ydev_hat2))
print('MSLE= %f' % metrics.mean_squared_log_error(ydev,ydev_hat2))
print('RMSLE= %f' % np.sqrt(metrics.mean_squared_log_error(ydev,ydev_hat2)))
print('R2= %f' % metrics.r2_score(ydev,ydev_hat2))

MSE= 0.940957
RMSE= 0.970029
MAE= 0.770139
MSLE= 0.031467
RMSLE= 0.177390
R2= 0.098852

In [61]:
MSE4B = metrics.mean_squared_error(ydev,ydev_hat2)
RMSE4B = np.sqrt(metrics.mean_squared_error(ydev,ydev_hat2))
MAE4B = metrics.mean_absolute_error(ydev,ydev_hat2)
MSLE4B = metrics.mean_squared_log_error(ydev,ydev_hat2)
R24B = metrics.r2_score(ydev,ydev_hat2)

## Decision tree

In [62]:
from sklearn.tree import DecisionTreeRegressor
dtree2= DecisionTreeRegressor(random_state=2).fit(X2,y)

In [63]:
y_hat2 = dtree2.predict(X2)

In [64]:
print('MSE= %f' % metrics.mean_squared_error(y,y_hat2))#, squared=False)) <--- version 0.44 +
print('RMSE= %f' % np.sqrt(metrics.mean_squared_error(y,y_hat2)))
print('MAE= %f' % metrics.mean_absolute_error(y,y_hat2))
print('MSLE= %f' % metrics.mean_squared_log_error(y,y_hat2))
print('RMSLE= %f' % np.sqrt(metrics.mean_squared_log_error(y,y_hat2)))
print('R2= %f' % metrics.r2_score(y,y_hat2))

MSE= 0.104607
RMSE= 0.323431
MAE= 0.132992
MSLE= 0.003484
RMSLE= 0.059029
R2= 0.899534

In [65]:
MSE5A = metrics.mean_squared_error(y,y_hat2)
RMSE5A = np.sqrt(metrics.mean_squared_error(y,y_hat2))
MAE5A = metrics.mean_absolute_error(y,y_hat2)
MSLE5A = metrics.mean_squared_log_error(y,y_hat2)
R25A = metrics.r2_score(y,y_hat2)

In [66]:
ydev_hat2 = dtree2.predict(Xdev2)

In [67]:
print('MSE= %f' % metrics.mean_squared_error(ydev,ydev_hat2))#, squared=False)) <--- version 0.22 +
print('RMSE= %f' % np.sqrt(metrics.mean_squared_error(ydev,ydev_hat2)))
print('MAE= %f' % metrics.mean_absolute_error(ydev,ydev_hat2))
print('MSLE= %f' % metrics.mean_squared_log_error(ydev,ydev_hat2))
print('R2= %f' % metrics.r2_score(ydev,ydev_hat2))

MSE= 0.609066
RMSE= 0.780427
MAE= 0.533675
MSLE= 0.021693
R2= 0.416702

In [68]:
MSE5B = metrics.mean_squared_error(ydev,ydev_hat2)
RMSE5B = np.sqrt(metrics.mean_squared_error(ydev,ydev_hat2))
MAE5B = metrics.mean_absolute_error(ydev,ydev_hat2)
MSLE5B = metrics.mean_squared_log_error(ydev,ydev_hat2)
R25B = metrics.r2_score(ydev,ydev_hat2)

In [98]:
metrics_sel = pd.DataFrame(columns= ['Model','MSE','RMSE','MAE','MSLE','R2'])

In [99]:
metrics_sel

Empty DataFrame
Columns: [Model, MSE, RMSE, MAE, MSLE, R2]
Index: []

In [100]:
add_row = pd.Series(['linear regression train',MSE1A,RMSE1A,MAE1A,MSLE1A,R21A],index=['Model','MSE','RMSE','MAE','MSLE','R2'])

In [101]:
add_row1 = pd.Series(['linear regression dev',MSE1B,RMSE1B,MAE1B,MSLE1B,R21B],index=['Model','MSE','RMSE','MAE','MSLE','R2'])

In [102]:
add_row2 = pd.Series(['Random forest train',MSE2A,RMSE2A,MAE2A,MSLE2A,R22A],index=['Model','MSE','RMSE','MAE','MSLE','R2'])

In [103]:
add_row3 = pd.Series(['Random forest dev',MSE2B,RMSE2B,MAE2B,MSLE2B,R22B],index=['Model','MSE','RMSE','MAE','MSLE','R2'])

In [104]:
add_row4 = pd.Series(['XGboost train',MSE3A,RMSE3A,MAE3A,MSLE3A,R23A],index=['Model','MSE','RMSE','MAE','MSLE','R2'])

In [105]:
add_row5 = pd.Series(['XGboost dev',MSE3B,RMSE3B,MAE3B,MSLE3B,R23B],index=['Model','MSE','RMSE','MAE','MSLE','R2'])

In [106]:
add_row6 = pd.Series(['Adaboost train',MSE4A,RMSE4A,MAE4A,MSLE4A,R24A],index=['Model','MSE','RMSE','MAE','MSLE','R2'])

In [107]:
add_row7 = pd.Series(['Adaboost dev',MSE4B,RMSE4B,MAE4B,MSLE4B,R24B],index=['Model','MSE','RMSE','MAE','MSLE','R2'])

In [108]:
add_row8 = pd.Series(['Decision tree train',MSE5A,RMSE5A,MAE5A,MSLE5A,R25A],index=['Model','MSE','RMSE','MAE','MSLE','R2'])

In [109]:
add_row9 = pd.Series(['Decision tree dev',MSE5B,RMSE5B,MAE5B,MSLE5B,R25B],index=['Model','MSE','RMSE','MAE','MSLE','R2'])

In [110]:
metrics_sel = metrics_sel.append(add_row, ignore_index=True)
metrics_sel = metrics_sel.append(add_row1, ignore_index=True)
metrics_sel = metrics_sel.append(add_row2, ignore_index=True)
metrics_sel = metrics_sel.append(add_row3, ignore_index=True)
metrics_sel = metrics_sel.append(add_row4, ignore_index=True)
metrics_sel = metrics_sel.append(add_row5, ignore_index=True)
metrics_sel = metrics_sel.append(add_row6, ignore_index=True)
metrics_sel = metrics_sel.append(add_row7, ignore_index=True)
metrics_sel = metrics_sel.append(add_row8, ignore_index=True)
metrics_sel = metrics_sel.append(add_row9, ignore_index=True)

In [111]:
metrics_sel

                     Model       MSE      RMSE       MAE      MSLE        R2
0  linear regression train  0.908753  0.953285  0.755750  0.030693  0.127223
1    linear regression dev  0.911509  0.954730  0.756612  0.030846  0.127054
2      Random forest train  0.139675  0.373732  0.227872  0.004868  0.865854
3        Random forest dev  0.425077  0.651980  0.446759  0.014937  0.592907
4            XGboost train  0.737664  0.858874  0.672583  0.025105  0.291539
5              XGboost dev  0.742225  0.861525  0.674458  0.025319  0.289177
6           Adaboost train  0.937782  0.968391  0.768766  0.031287  0.099343
7             Adaboost dev  0.940957  0.970029  0.770139  0.031467  0.098852
8      Decision tree train  0.104607  0.323431  0.132992  0.003484  0.899534
9        Decision tree dev  0.609066  0.780427  0.533675  0.021693  0.416702

 it seems to be that random forest and decision tree models had the best results and score but on the other hand they were very unstable and it is clear that they have a big difference between the train and the dev score by all the metrics. 
Therefore, i decided to choose the XGboost model which is much more stable.