# Feature Selection Strategy

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv("../data/numeric_feature_table.csv")
df.head()

,id,item_nbr,store_nbr,Year,month,prev_month_sales,prev_3month_sales,avg_prev_3months_sales,min_prev_3months_sales,max_prev_3months_sales,...,cluster9,cluster10,cluster11,cluster12,cluster13,cluster14,cluster15,cluster16,cluster17,total_unit_sales
0,1,1003679,1,2013,4,3.850148,3.988984,4.071872,3.784190,4.454347,...,0,0,0,0,1,0,0,0,0,3.806662
1,2,1003679,1,2013,5,3.806662,4.465908,3.799228,3.784190,3.828641,...,0,0,0,0,1,0,0,0,0,3.806662
2,3,1003679,1,2013,6,3.806662,3.850148,3.806662,3.784190,3.850148,...,0,0,0,0,1,0,0,0,0,3.871201
3,4,1003679,1,2013,7,3.871201,3.806662,3.688879,3.367296,3.850148,...,0,0,0,0,1,0,0,0,0,3.401197
4,5,1003679,1,2013,8,3.401197,3.806662,3.637586,3.367296,3.850148,...,0,0,0,0,1,0,0,0,0,3.663562

In [3]:
#df['rejected'] = df['rejected'].astype('category')
#df['condition'] = df['condition'].astype('category')

df.dtypes

id                                 int64
item_nbr                           int64
store_nbr                          int64
Year                               int64
month                              int64
prev_month_sales                 float64
prev_3month_sales                float64
avg_prev_3months_sales           float64
min_prev_3months_sales           float64
max_prev_3months_sales           float64
monthly_oilprice_avg             float64
total_month_holidays               int64
total_month_transactions           int64
prev_month_transactions            int64
prev_3month_transactions           int64
avg_prev_3months_transactions    float64
min_prev_3months_transactions      int64
max_prev_3months_transactions      int64
BREAD.BAKERY                       int64
BEVERAGES                          int64
DAIRY                              int64
PERSONAL.CARE                      int64
HOME.CARE                          int64
FROZEN.FOODS                       int64
POULTRY                            int64
GROCERY.II                         int64
X.LIQUOR                           int64
EGGS                               int64
GROCERY.I                          int64
CLEANING                           int64
                                  ...
city_Loja                          int64
city_Machala                       int64
city_Manta                         int64
city_Playas                        int64
city_Puyo                          int64
city_Quevedo                       int64
city_Quito                         int64
city_Riobamba                      int64
city_Salinas                       int64
city_Santo.Domingo                 int64
total_city_sales                 float64
sales_perc                       float64
cluster1                           int64
cluster2                           int64
cluster3                           int64
cluster4                           int64
cluster5                           int64
cluster6                           int64
cluster7                           int64
cluster8                           int64
cluster9                           int64
cluster10                          int64
cluster11                          int64
cluster12                          int64
cluster13                          int64
cluster14                          int64
cluster15                          int64
cluster16                          int64
cluster17                          int64
total_unit_sales                 float64
Length: 78, dtype: object

In [4]:
df.shape

(1734047, 78)

In [5]:
varSel = pd.DataFrame({'Variable': df.columns[1:77]})
varSel

                         Variable
0                        item_nbr
1                       store_nbr
2                            Year
3                           month
4                prev_month_sales
5               prev_3month_sales
6          avg_prev_3months_sales
7          min_prev_3months_sales
8          max_prev_3months_sales
9            monthly_oilprice_avg
10           total_month_holidays
11       total_month_transactions
12        prev_month_transactions
13       prev_3month_transactions
14  avg_prev_3months_transactions
15  min_prev_3months_transactions
16  max_prev_3months_transactions
17                   BREAD.BAKERY
18                      BEVERAGES
19                          DAIRY
20                  PERSONAL.CARE
21                      HOME.CARE
22                   FROZEN.FOODS
23                        POULTRY
24                     GROCERY.II
25                       X.LIQUOR
26                           EGGS
27                      GROCERY.I
28                       CLEANING
29                           DELI
..                            ...
46                  city_Libertad
47                      city_Loja
48                   city_Machala
49                     city_Manta
50                    city_Playas
51                      city_Puyo
52                   city_Quevedo
53                     city_Quito
54                  city_Riobamba
55                   city_Salinas
56             city_Santo.Domingo
57               total_city_sales
58                     sales_perc
59                       cluster1
60                       cluster2
61                       cluster3
62                       cluster4
63                       cluster5
64                       cluster6
65                       cluster7
66                       cluster8
67                       cluster9
68                      cluster10
69                      cluster11
70                      cluster12
71                      cluster13
72                      cluster14
73                      cluster15
74                      cluster16
75                      cluster17

[76 rows x 1 columns]

## Multivariable Analysis

In [7]:
### drop na
##df = df.dropna()

In [6]:
## remove unnecessary vars
X = df.loc[:,df.columns[1:77]]
X.head()

,item_nbr,store_nbr,Year,month,prev_month_sales,prev_3month_sales,avg_prev_3months_sales,min_prev_3months_sales,max_prev_3months_sales,monthly_oilprice_avg,...,cluster8,cluster9,cluster10,cluster11,cluster12,cluster13,cluster14,cluster15,cluster16,cluster17
0,1003679,1,2013,4,3.850148,3.988984,4.071872,3.784190,4.454347,92.021364,...,0,0,0,0,0,1,0,0,0,0
1,1003679,1,2013,5,3.806662,4.465908,3.799228,3.784190,3.828641,94.509545,...,0,0,0,0,0,1,0,0,0,0
2,1003679,1,2013,6,3.806662,3.850148,3.806662,3.784190,3.850148,95.772500,...,0,0,0,0,0,1,0,0,0,0
3,1003679,1,2013,7,3.871201,3.806662,3.688879,3.367296,3.850148,104.670909,...,0,0,0,0,0,1,0,0,0,0
4,1003679,1,2013,8,3.401197,3.806662,3.637586,3.367296,3.850148,106.572727,...,0,0,0,0,0,1,0,0,0,0

In [7]:
 y = df.loc[:,df.columns[77]]
print([X.shape,y.shape])

[(1734047, 76), (1734047,)]

In [8]:
y

0          3.806662
1          3.806662
2          3.871201
3          3.401197
4          3.663562
5          3.912023
6          3.637586
7          4.043051
8          5.298317
9          3.828641
10         4.343805
11         4.262680
12         4.158883
13         3.663562
14         3.637586
15         3.713572
16         3.555348
17         3.828641
18         3.610918
19         5.913503
20         3.784190
21         4.262680
22         4.143135
23         4.343805
24         4.634729
25         4.454347
26         3.828641
27         3.784190
28         3.931826
29         3.761200
             ...
1734017    5.666427
1734018    5.710427
1734019    5.755742
1734020    5.332719
1734021    5.634790
1734022    5.886104
1734023    6.001415
1734024    5.438079
1734025    5.823046
1734026    5.659482
1734027    5.398163
1734028    5.476464
1734029    5.407172
1734030    5.627621
1734031    5.393628
1734032    5.513429
1734033    4.574711
1734034    4.584967
1734035    4.795791
1734036    4.691348
1734037    4.584967
1734038    5.105945
1734039    5.283204
1734040    5.111988
1734041    5.003946
1734042    4.990433
1734043    5.198497
1734044    5.214936
1734045    5.278115
1734046    4.859812
Name: total_unit_sales, Length: 1734047, dtype: float64

### Variable Selection using LASSO (L1 penalization)

In [9]:
from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel

lassomod = Lasso(alpha=0.05).fit(X, y)

C:\Users\Guy\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 94457.39410569871, tolerance: 178.41123745046016
  positive)

In [10]:
model = SelectFromModel(lassomod, prefit=True)
model.get_support()

array([False, False, False, False, False, False,  True,  True,  True,
        True, False,  True, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [11]:
varSel['Lasso'] = model.get_support().astype('int64')
varSel

                         Variable  Lasso
0                        item_nbr      0
1                       store_nbr      0
2                            Year      0
3                           month      0
4                prev_month_sales      0
5               prev_3month_sales      0
6          avg_prev_3months_sales      1
7          min_prev_3months_sales      1
8          max_prev_3months_sales      1
9            monthly_oilprice_avg      1
10           total_month_holidays      0
11       total_month_transactions      1
12        prev_month_transactions      0
13       prev_3month_transactions      0
14  avg_prev_3months_transactions      1
15  min_prev_3months_transactions      0
16  max_prev_3months_transactions      0
17                   BREAD.BAKERY      0
18                      BEVERAGES      0
19                          DAIRY      0
20                  PERSONAL.CARE      0
21                      HOME.CARE      0
22                   FROZEN.FOODS      0
23                        POULTRY      0
24                     GROCERY.II      0
25                       X.LIQUOR      0
26                           EGGS      0
27                      GROCERY.I      0
28                       CLEANING      0
29                           DELI      0
..                            ...    ...
46                  city_Libertad      0
47                      city_Loja      0
48                   city_Machala      0
49                     city_Manta      0
50                    city_Playas      0
51                      city_Puyo      0
52                   city_Quevedo      0
53                     city_Quito      0
54                  city_Riobamba      0
55                   city_Salinas      0
56             city_Santo.Domingo      0
57               total_city_sales      0
58                     sales_perc      0
59                       cluster1      0
60                       cluster2      0
61                       cluster3      0
62                       cluster4      0
63                       cluster5      0
64                       cluster6      0
65                       cluster7      0
66                       cluster8      0
67                       cluster9      0
68                      cluster10      0
69                      cluster11      0
70                      cluster12      0
71                      cluster13      0
72                      cluster14      0
73                      cluster15      0
74                      cluster16      0
75                      cluster17      0

[76 rows x 2 columns]

### Variable Selection using Random Forest

In [12]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import SelectFromModel

rfmod = RandomForestRegressor().fit(X, y)
#rfmod.feature_importances_

C:\Users\Guy\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [13]:
model = SelectFromModel(rfmod, prefit=True)
model.get_support()

array([False, False, False, False,  True, False,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [14]:
varSel['RandomForest'] = model.get_support().astype('int64')
varSel

                         Variable  Lasso  RandomForest
0                        item_nbr      0             0
1                       store_nbr      0             0
2                            Year      0             0
3                           month      0             0
4                prev_month_sales      0             1
5               prev_3month_sales      0             0
6          avg_prev_3months_sales      1             1
7          min_prev_3months_sales      1             1
8          max_prev_3months_sales      1             0
9            monthly_oilprice_avg      1             0
10           total_month_holidays      0             0
11       total_month_transactions      1             0
12        prev_month_transactions      0             0
13       prev_3month_transactions      0             0
14  avg_prev_3months_transactions      1             0
15  min_prev_3months_transactions      0             0
16  max_prev_3months_transactions      0             0
17                   BREAD.BAKERY      0             0
18                      BEVERAGES      0             0
19                          DAIRY      0             0
20                  PERSONAL.CARE      0             0
21                      HOME.CARE      0             0
22                   FROZEN.FOODS      0             0
23                        POULTRY      0             0
24                     GROCERY.II      0             0
25                       X.LIQUOR      0             0
26                           EGGS      0             0
27                      GROCERY.I      0             0
28                       CLEANING      0             0
29                           DELI      0             0
..                            ...    ...           ...
46                  city_Libertad      0             0
47                      city_Loja      0             0
48                   city_Machala      0             0
49                     city_Manta      0             0
50                    city_Playas      0             0
51                      city_Puyo      0             0
52                   city_Quevedo      0             0
53                     city_Quito      0             0
54                  city_Riobamba      0             0
55                   city_Salinas      0             0
56             city_Santo.Domingo      0             0
57               total_city_sales      0             0
58                     sales_perc      0             0
59                       cluster1      0             0
60                       cluster2      0             0
61                       cluster3      0             0
62                       cluster4      0             0
63                       cluster5      0             0
64                       cluster6      0             0
65                       cluster7      0             0
66                       cluster8      0             0
67                       cluster9      0             0
68                      cluster10      0             0
69                      cluster11      0             0
70                      cluster12      0             0
71                      cluster13      0             0
72                      cluster14      0             0
73                      cluster15      0             0
74                      cluster16      0             0
75                      cluster17      0             0

[76 rows x 3 columns]

### Variable Selection using Gradient Boosting classification

In [15]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.feature_selection import SelectFromModel

gbmod = GradientBoostingRegressor().fit(X,y)

In [16]:
model = SelectFromModel(gbmod, prefit=True)
model.get_support()

array([False, False, False, False, False, False,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [17]:
varSel['GradientBoost'] = model.get_support().astype('int64')
varSel

                         Variable  Lasso  RandomForest  GradientBoost
0                        item_nbr      0             0              0
1                       store_nbr      0             0              0
2                            Year      0             0              0
3                           month      0             0              0
4                prev_month_sales      0             1              0
5               prev_3month_sales      0             0              0
6          avg_prev_3months_sales      1             1              1
7          min_prev_3months_sales      1             1              1
8          max_prev_3months_sales      1             0              0
9            monthly_oilprice_avg      1             0              0
10           total_month_holidays      0             0              0
11       total_month_transactions      1             0              0
12        prev_month_transactions      0             0              0
13       prev_3month_transactions      0             0              0
14  avg_prev_3months_transactions      1             0              0
15  min_prev_3months_transactions      0             0              0
16  max_prev_3months_transactions      0             0              0
17                   BREAD.BAKERY      0             0              0
18                      BEVERAGES      0             0              0
19                          DAIRY      0             0              0
20                  PERSONAL.CARE      0             0              0
21                      HOME.CARE      0             0              0
22                   FROZEN.FOODS      0             0              0
23                        POULTRY      0             0              0
24                     GROCERY.II      0             0              0
25                       X.LIQUOR      0             0              0
26                           EGGS      0             0              0
27                      GROCERY.I      0             0              0
28                       CLEANING      0             0              0
29                           DELI      0             0              0
..                            ...    ...           ...            ...
46                  city_Libertad      0             0              0
47                      city_Loja      0             0              0
48                   city_Machala      0             0              0
49                     city_Manta      0             0              0
50                    city_Playas      0             0              0
51                      city_Puyo      0             0              0
52                   city_Quevedo      0             0              0
53                     city_Quito      0             0              0
54                  city_Riobamba      0             0              0
55                   city_Salinas      0             0              0
56             city_Santo.Domingo      0             0              0
57               total_city_sales      0             0              0
58                     sales_perc      0             0              0
59                       cluster1      0             0              0
60                       cluster2      0             0              0
61                       cluster3      0             0              0
62                       cluster4      0             0              0
63                       cluster5      0             0              0
64                       cluster6      0             0              0
65                       cluster7      0             0              0
66                       cluster8      0             0              0
67                       cluster9      0             0              0
68                      cluster10      0             0              0
69                      cluster11      0             0              0
70                      cluster12      0             0              0
71                      cluster13      0             0              0
72                      cluster14      0             0              0
73                      cluster15      0             0              0
74                      cluster16      0             0              0
75                      cluster17      0             0              0

[76 rows x 4 columns]

### Variable Selection using SVM classification

In [ ]:
from sklearn import svm
from sklearn.feature_selection import SelectFromModel

svmmod = svm.SVR( C=1, gamma=0.1).fit(X, y)

In [ ]:
model = SelectFromModel(svmmod, prefit=True)
model.get_support()

In [ ]:
varSel['SVM'] = model.get_support().astype('int64')
varSel

# Ada Boost

In [16]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn.feature_selection import SelectFromModel

ABRmod = AdaBoostRegressor(random_state=1).fit(X,y)

In [18]:
model = SelectFromModel(ABRmod, prefit=True)
model.get_support()

array([False,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [19]:
varSel['Ada Boost'] = model.get_support().astype('int64')
varSel

,Variable,Lasso,RandomForest,GradientBoost,Ada Boost
0,Year,1,0,0,0
1,month,1,0,0,1
2,prev_month_sales,1,1,0,1
3,prev_3month_sales,1,0,0,1
4,avg_prev_3months_sales,1,1,1,1
5,min_prev_3months_sales,1,1,1,1
6,max_prev_3months_sales,1,1,1,1
7,monthly_oilprice_avg,1,0,0,0
8,total_month_holidays,1,0,0,0
9,total_month_transactions,1,0,0,0
10,prev_month_transactions,1,0,0,0
11,prev_3month_transactions,1,0,0,0
12,avg_prev_3months_transactions,1,0,0,0
13,min_prev_3months_transactions,1,0,0,0
14,max_prev_3months_transactions,1,0,0,0
15,BREAD.BAKERY,0,0,0,0
16,BEVERAGES,0,0,0,0
17,DAIRY,0,0,0,0
18,PERSONAL.CARE,0,0,0,0
19,HOME.CARE,0,0,0,0
20,FROZEN.FOODS,0,0,0,0
21,POULTRY,0,0,0,0
22,GROCERY.II,0,0,0,0
23,X.LIQUOR,0,0,0,0
24,EGGS,0,0,0,0
25,GROCERY.I,1,0,0,0
26,CLEANING,0,0,0,0
27,DELI,0,0,0,0
28,store_typeA,0,0,0,0
29,store_typeB,0,0,0,0
...,...,...,...,...,...
44,city_Libertad,0,0,0,0
45,city_Loja,0,0,0,0
46,city_Machala,0,0,0,0
47,city_Manta,0,0,0,0
48,city_Playas,0,0,0,0
49,city_Puyo,0,0,0,0
50,city_Quevedo,0,0,0,0
51,city_Quito,0,0,0,0
52,city_Riobamba,0,0,0,0
53,city_Salinas,0,0,0,0
54,city_Santo.Domingo,0,0,0,0
55,total_city_sales,0,0,0,0
56,sales_perc,1,0,0,0
57,cluster1,0,0,0,0
58,cluster2,0,0,0,0
59,cluster3,0,0,0,0
60,cluster4,0,0,0,0
61,cluster5,0,0,0,0
62,cluster6,0,0,0,0
63,cluster7,0,0,0,0
64,cluster8,0,0,0,0
65,cluster9,0,0,0,0
66,cluster10,0,0,0,0
67,cluster11,0,0,0,0
68,cluster12,0,0,0,0
69,cluster13,0,0,0,0
70,cluster14,0,0,0,0
71,cluster15,0,0,0,0
72,cluster16,0,0,0,0
73,cluster17,0,0,0,0

## KNN

In [34]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.feature_selection import SelectFromModel
neigh = KNeighborsRegressor(n_neighbors=5).fit(X, y)

In [35]:
from sklearn.feature_selection import SelectFromModel
model = SelectFromModel(neigh, prefit=True)
model.get_support()

ValueError: The underlying estimator KNeighborsRegressor has no `coef_` or `feature_importances_` attribute. Either pass a fitted estimator to SelectFromModel or call fit before calling transform.

In [ ]:
varSel['KNN'] = model.get_support().astype('int64')
varSel

## Ridge L2 regularization

In [36]:
from sklearn.linear_model import Ridge
from sklearn.feature_selection import SelectFromModel
Rdg = Ridge(alpha=0.5).fit(X,y)

C:\Users\Guy\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=8.67136e-20): result may not be accurate.
  overwrite_a=True).T

In [37]:
model = SelectFromModel(Rdg, prefit=True)
model.get_support()

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
        True, False, False,  True,  True,  True, False,  True, False,
       False, False, False, False, False, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True, False,  True,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False])

In [38]:
varSel['Ridge'] = model.get_support().astype('int64')
varSel

,Variable,Lasso,RandomForest,GradientBoost,Ada Boost,Ridge
0,Year,1,0,0,0,0
1,month,1,0,0,1,0
2,prev_month_sales,1,1,0,1,0
3,prev_3month_sales,1,0,0,1,0
4,avg_prev_3months_sales,1,1,1,1,1
5,min_prev_3months_sales,1,1,1,1,0
6,max_prev_3months_sales,1,1,1,1,0
7,monthly_oilprice_avg,1,0,0,0,0
8,total_month_holidays,1,0,0,0,0
9,total_month_transactions,1,0,0,0,0
10,prev_month_transactions,1,0,0,0,0
11,prev_3month_transactions,1,0,0,0,0
12,avg_prev_3months_transactions,1,0,0,0,0
13,min_prev_3months_transactions,1,0,0,0,0
14,max_prev_3months_transactions,1,0,0,0,0
15,BREAD.BAKERY,0,0,0,0,0
16,BEVERAGES,0,0,0,0,1
17,DAIRY,0,0,0,0,0
18,PERSONAL.CARE,0,0,0,0,1
19,HOME.CARE,0,0,0,0,0
20,FROZEN.FOODS,0,0,0,0,0
21,POULTRY,0,0,0,0,1
22,GROCERY.II,0,0,0,0,1
23,X.LIQUOR,0,0,0,0,1
24,EGGS,0,0,0,0,0
25,GROCERY.I,1,0,0,0,1
26,CLEANING,0,0,0,0,0
27,DELI,0,0,0,0,0
28,store_typeA,0,0,0,0,0
29,store_typeB,0,0,0,0,0
...,...,...,...,...,...,...
44,city_Libertad,0,0,0,0,1
45,city_Loja,0,0,0,0,1
46,city_Machala,0,0,0,0,0
47,city_Manta,0,0,0,0,1
48,city_Playas,0,0,0,0,1
49,city_Puyo,0,0,0,0,0
50,city_Quevedo,0,0,0,0,1
51,city_Quito,0,0,0,0,1
52,city_Riobamba,0,0,0,0,0
53,city_Salinas,0,0,0,0,1
54,city_Santo.Domingo,0,0,0,0,0
55,total_city_sales,0,0,0,0,0
56,sales_perc,1,0,0,0,0
57,cluster1,0,0,0,0,0
58,cluster2,0,0,0,0,0
59,cluster3,0,0,0,0,0
60,cluster4,0,0,0,0,0
61,cluster5,0,0,0,0,0
62,cluster6,0,0,0,0,0
63,cluster7,0,0,0,0,1
64,cluster8,0,0,0,0,0
65,cluster9,0,0,0,0,0
66,cluster10,0,0,0,0,0
67,cluster11,0,0,0,0,0
68,cluster12,0,0,0,0,0
69,cluster13,0,0,0,0,0
70,cluster14,0,0,0,0,0
71,cluster15,0,0,0,0,0
72,cluster16,0,0,0,0,0
73,cluster17,0,0,0,0,0

## Decision tree

In [39]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.feature_selection import SelectFromModel
dtree= DecisionTreeRegressor(random_state=2).fit(X,y)

In [40]:
model = SelectFromModel(dtree, prefit=True)
model.get_support()

array([False, False,  True, False,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [41]:
varSel['dtree'] = model.get_support().astype('int64')
varSel

,Variable,Lasso,RandomForest,GradientBoost,Ada Boost,Ridge,dtree
0,Year,1,0,0,0,0,0
1,month,1,0,0,1,0,0
2,prev_month_sales,1,1,0,1,0,1
3,prev_3month_sales,1,0,0,1,0,0
4,avg_prev_3months_sales,1,1,1,1,1,1
5,min_prev_3months_sales,1,1,1,1,0,1
6,max_prev_3months_sales,1,1,1,1,0,1
7,monthly_oilprice_avg,1,0,0,0,0,0
8,total_month_holidays,1,0,0,0,0,0
9,total_month_transactions,1,0,0,0,0,0
10,prev_month_transactions,1,0,0,0,0,0
11,prev_3month_transactions,1,0,0,0,0,0
12,avg_prev_3months_transactions,1,0,0,0,0,0
13,min_prev_3months_transactions,1,0,0,0,0,0
14,max_prev_3months_transactions,1,0,0,0,0,0
15,BREAD.BAKERY,0,0,0,0,0,0
16,BEVERAGES,0,0,0,0,1,0
17,DAIRY,0,0,0,0,0,0
18,PERSONAL.CARE,0,0,0,0,1,0
19,HOME.CARE,0,0,0,0,0,0
20,FROZEN.FOODS,0,0,0,0,0,0
21,POULTRY,0,0,0,0,1,0
22,GROCERY.II,0,0,0,0,1,0
23,X.LIQUOR,0,0,0,0,1,0
24,EGGS,0,0,0,0,0,0
25,GROCERY.I,1,0,0,0,1,0
26,CLEANING,0,0,0,0,0,0
27,DELI,0,0,0,0,0,0
28,store_typeA,0,0,0,0,0,0
29,store_typeB,0,0,0,0,0,0
...,...,...,...,...,...,...,...
44,city_Libertad,0,0,0,0,1,0
45,city_Loja,0,0,0,0,1,0
46,city_Machala,0,0,0,0,0,0
47,city_Manta,0,0,0,0,1,0
48,city_Playas,0,0,0,0,1,0
49,city_Puyo,0,0,0,0,0,0
50,city_Quevedo,0,0,0,0,1,0
51,city_Quito,0,0,0,0,1,0
52,city_Riobamba,0,0,0,0,0,0
53,city_Salinas,0,0,0,0,1,0
54,city_Santo.Domingo,0,0,0,0,0,0
55,total_city_sales,0,0,0,0,0,0
56,sales_perc,1,0,0,0,0,0
57,cluster1,0,0,0,0,0,0
58,cluster2,0,0,0,0,0,0
59,cluster3,0,0,0,0,0,0
60,cluster4,0,0,0,0,0,0
61,cluster5,0,0,0,0,0,0
62,cluster6,0,0,0,0,0,0
63,cluster7,0,0,0,0,1,0
64,cluster8,0,0,0,0,0,0
65,cluster9,0,0,0,0,0,0
66,cluster10,0,0,0,0,0,0
67,cluster11,0,0,0,0,0,0
68,cluster12,0,0,0,0,0,0
69,cluster13,0,0,0,0,0,0
70,cluster14,0,0,0,0,0,0
71,cluster15,0,0,0,0,0,0
72,cluster16,0,0,0,0,0,0
73,cluster17,0,0,0,0,0,0

## XG boost

In [ ]:
from sklearn import svm
from sklearn.feature_selection import SelectFromModel
clf = svm.SVR(C=1, gamma=0.1).fit(X,y)

### Summarization and Selection of Variables

In [1]:
varSel['Sum'] =  np.sum(varSel,axis=1)
varSel

NameError: name 'np' is not defined

In [133]:
varSel.groupby('Sum')['Variable'].count()

Sum
0     3
1     4
2     4
3     8
4    10
5     7
Name: Variable, dtype: int64

We can now decide a threshold for selecting our variables!